# @generated by restack-gen v1.0.0 (2025-10-24T14:57:21.644758+00:00)
# command:
"""Client script to schedule TestAgent agent."""

import asyncio

from restack_ai import Restack

# from restack-gen.agents. import TestAgent, TestAgentState


async def main() -> None:
    """Schedule TestAgent agent."""
    client = Restack()

    # Create initial state
    initial_state = TestAgentState(
        # TODO: Set initial state fields
    )

    # Schedule agent
    workflow_id = ""
    run_id = await client.schedule_workflow(
        workflow=TestAgent,
        workflow_id=workflow_id,
        input=initial_state,
        task_queue="",
    )

    print(f"Scheduled TestAgent: workflow_id={workflow_id}, run_id={run_id}")

    # TODO: Send events to agent
    # await client.send_workflow_signal(
    #     workflow_id=workflow_id,
    #     signal="TestAgent.handle_event",
    #     input={"event": "some_event", "payload": {}},
    # )


if __name__ == "__main__":
    asyncio.run(main())
