"""Tests for resource generation (agents, workflows, functions)."""

import pytest
from pathlib import Path

from restack_gen.generator import (
    GenerationError,
    generate_agent,
    generate_function,
    generate_workflow,
    find_project_root,
    get_project_name,
    to_pascal_case,
    to_snake_case,
    validate_name,
)
from restack_gen.project import create_new_project


class TestNameConversion:
    """Test name conversion utilities."""

    def test_to_snake_case(self):
        assert to_snake_case("MyAgent") == "my_agent"
        assert to_snake_case("EmailWorkflow") == "email_workflow"
        assert to_snake_case("SendEmail") == "send_email"
        assert to_snake_case("lowercase") == "lowercase"

    def test_to_pascal_case(self):
        assert to_pascal_case("my_agent") == "MyAgent"
        assert to_pascal_case("email_workflow") == "EmailWorkflow"
        assert to_pascal_case("send_email") == "SendEmail"
        assert to_pascal_case("single") == "Single"


class TestNameValidation:
    """Test resource name validation."""

    def test_valid_names(self):
        valid_names = [
            "my_agent",
            "MyAgent",
            "workflow",
            "send_email",
            "_private",
        ]
        for name in valid_names:
            is_valid, error = validate_name(name)
            assert is_valid, f"{name} should be valid: {error}"

    def test_empty_name(self):
        is_valid, error = validate_name("")
        assert not is_valid
        assert "empty" in error.lower()

    def test_invalid_characters(self):
        invalid_names = ["my-agent", "my.workflow", "my agent", "my@function"]
        for name in invalid_names:
            is_valid, error = validate_name(name)
            assert not is_valid, f"{name} should be invalid"


class TestAgentGeneration:
    """Test agent generation."""

    @pytest.fixture
    def test_project(self, tmp_path):
        """Create a test project."""
        project_path = tmp_path / "testproject"
        create_new_project("testproject", parent_dir=tmp_path, force=False)
        return project_path

    def test_generate_agent_creates_files(self, test_project, monkeypatch):
        """Test that agent generation creates all expected files."""
        monkeypatch.chdir(test_project)

        files = generate_agent("researcher")

        assert files["agent"].exists()
        assert files["test"].exists()
        assert files["client"].exists()

        # Check file contains expected content
        agent_content = files["agent"].read_text()
        assert "class ResearcherAgent:" in agent_content
        assert "@generated by restack-gen" in agent_content
        assert "ResearcherAgentEvent" in agent_content

    def test_generate_agent_updates_service(self, test_project, monkeypatch):
        """Test that agent generation updates service.py."""
        monkeypatch.chdir(test_project)

        generate_agent("data")

        service_file = test_project / "server" / "service.py"
        service_content = service_file.read_text()

        # Check import added
        assert "from testproject.agents.data import DataAgent" in service_content
        # Check registration added
        assert "DataAgent," in service_content
        assert "workflows=[" in service_content

    def test_generate_agent_idempotency(self, test_project, monkeypatch):
        """Test that generating same agent twice fails without --force."""
        monkeypatch.chdir(test_project)

        generate_agent("analyzer")

        with pytest.raises(GenerationError, match="already exists"):
            generate_agent("analyzer")

    def test_generate_agent_force_overwrites(self, test_project, monkeypatch):
        """Test that --force flag allows overwriting."""
        monkeypatch.chdir(test_project)

        files1 = generate_agent("processor")
        files2 = generate_agent("processor", force=True)

        assert files1["agent"] == files2["agent"]
        assert files2["agent"].exists()

    def test_generate_agent_no_duplicates_in_service(self, test_project, monkeypatch):
        """Test that service.py doesn't get duplicate entries."""
        monkeypatch.chdir(test_project)

        generate_agent("cleaner")
        generate_agent("cleaner", force=True)

        service_file = test_project / "server" / "service.py"
        service_content = service_file.read_text()

        # Should only appear once
        assert service_content.count("DataAgent") == 0  # Not generated yet
        assert service_content.count("CleanerAgent,") == 1
        assert service_content.count("from testproject.agents.cleaner import CleanerAgent") == 1


class TestWorkflowGeneration:
    """Test workflow generation."""

    @pytest.fixture
    def test_project(self, tmp_path):
        """Create a test project."""
        project_path = tmp_path / "testproject"
        create_new_project("testproject", parent_dir=tmp_path, force=False)
        return project_path

    def test_generate_workflow_creates_files(self, test_project, monkeypatch):
        """Test that workflow generation creates all expected files."""
        monkeypatch.chdir(test_project)

        files = generate_workflow("email")

        assert files["workflow"].exists()
        assert files["test"].exists()
        assert files["client"].exists()

        # Check file contains expected content
        workflow_content = files["workflow"].read_text()
        assert "class EmailWorkflow:" in workflow_content
        assert "@generated by restack-gen" in workflow_content

    def test_generate_workflow_updates_service(self, test_project, monkeypatch):
        """Test that workflow generation updates service.py."""
        monkeypatch.chdir(test_project)

        generate_workflow("notification")

        service_file = test_project / "server" / "service.py"
        service_content = service_file.read_text()

        # Check import added
        assert (
            "from testproject.workflows.notification import NotificationWorkflow" in service_content
        )
        # Check registration added
        assert "NotificationWorkflow," in service_content


class TestFunctionGeneration:
    """Test function generation."""

    @pytest.fixture
    def test_project(self, tmp_path):
        """Create a test project."""
        project_path = tmp_path / "testproject"
        create_new_project("testproject", parent_dir=tmp_path, force=False)
        return project_path

    def test_generate_function_creates_files(self, test_project, monkeypatch):
        """Test that function generation creates all expected files."""
        monkeypatch.chdir(test_project)

        files = generate_function("send_email")

        assert files["function"].exists()
        assert files["test"].exists()
        assert "client" not in files  # Functions don't have client scripts

        # Check file contains expected content
        function_content = files["function"].read_text()
        assert "def send_email(" in function_content
        assert "@generated by restack-gen" in function_content

    def test_generate_function_updates_service(self, test_project, monkeypatch):
        """Test that function generation updates service.py."""
        monkeypatch.chdir(test_project)

        generate_function("transform_data")

        service_file = test_project / "server" / "service.py"
        service_content = service_file.read_text()

        # Check import added
        assert "from testproject.functions.transform_data import transform_data" in service_content
        # Check registration added
        assert "transform_data," in service_content
        assert "functions=[" in service_content


class TestMixedGeneration:
    """Test generating multiple resource types together."""

    @pytest.fixture
    def test_project(self, tmp_path):
        """Create a test project."""
        project_path = tmp_path / "testproject"
        create_new_project("testproject", parent_dir=tmp_path, force=False)
        return project_path

    def test_generate_all_types(self, test_project, monkeypatch):
        """Test generating agent, workflow, and function together."""
        monkeypatch.chdir(test_project)

        generate_agent("data")
        generate_workflow("process")
        generate_function("transform")

        service_file = test_project / "server" / "service.py"
        service_content = service_file.read_text()

        # Check all imports present
        assert "from testproject.agents.data import DataAgent" in service_content
        assert "from testproject.workflows.process import ProcessWorkflow" in service_content
        assert "from testproject.functions.transform import transform" in service_content

        # Check all registrations present
        assert "workflows=[" in service_content
        assert "DataAgent," in service_content
        assert "ProcessWorkflow," in service_content
        assert "functions=[" in service_content
        assert "transform," in service_content

    def test_service_file_structure(self, test_project, monkeypatch):
        """Test that service.py maintains correct structure."""
        monkeypatch.chdir(test_project)

        generate_function("first_func")
        generate_workflow("first_work")
        generate_agent("first_agent")

        service_file = test_project / "server" / "service.py"
        service_content = service_file.read_text()

        # Imports should be grouped by type
        func_import_pos = service_content.find("# Functions")
        work_import_pos = service_content.find("# Workflows")
        agent_import_pos = service_content.find("# Agents")

        # Check section order (may vary based on generation order)
        assert func_import_pos > 0
        assert work_import_pos > 0
        assert agent_import_pos > 0


class TestProjectContext:
    """Test project context utilities."""

    def test_find_project_root_from_subdirectory(self, tmp_path):
        """Test finding project root from subdirectory."""
        project_path = tmp_path / "myproject"
        create_new_project("myproject", parent_dir=tmp_path, force=False)

        # Create subdirectory and check from there
        subdir = project_path / "src" / "myproject"
        import os

        os.chdir(subdir)

        root = find_project_root()
        assert root == project_path

    def test_get_project_name(self, tmp_path):
        """Test extracting project name from pyproject.toml."""
        project_path = tmp_path / "testapp"
        create_new_project("testapp", parent_dir=tmp_path, force=False)

        name = get_project_name(project_path)
        assert name == "testapp"

    def test_generate_outside_project_fails(self, tmp_path, monkeypatch):
        """Test that generation fails outside a project."""
        monkeypatch.chdir(tmp_path)

        with pytest.raises(GenerationError, match="Not in a restack-gen project"):
            generate_agent("test")
