# @generated by restack-gen v1.0.0 (2025-10-26T04:27:12.226365+00:00)
# command: restack new testdemo
"""Settings for testdemo."""

from pathlib import Path

from testdemo.common.compat import Field, SettingsBase


class PipelineLoopSettings(SettingsBase):
    """Loop-specific settings."""

    max: int = Field(default=10, description="Maximum loop iterations")


class PipelineSettings(SettingsBase):
    """Pipeline-related settings."""

    # Using simplified approach for compatibility
    class Config:
        """Pydantic configuration."""

        extra = "allow"


class Settings(SettingsBase):
    """Application settings with environment variable support."""

    # Restack connection
    restack_engine_id: str = Field(
        default="",
        description="Restack engine ID (leave empty for local)",
    )
    restack_engine_address: str = Field(
        default="http://localhost:5233",
        description="Restack engine address",
    )

    # Service settings
    task_queue: str = Field(
        default="testdemo",
        description="Default task queue name",
    )
    default_timeout: int = Field(
        default=300,
        description="Default timeout in seconds",
    )
    default_heartbeat: int = Field(
        default=30,
        description="Default heartbeat interval in seconds",
    )

    # Agent settings
    agent_event_timeout: int = Field(
        default=3600,
        description="Agent event wait timeout in seconds",
    )

    # Pipeline settings (initialized with default instance)
    pipeline: PipelineSettings = PipelineSettings()

    class Config:
        """Pydantic settings configuration."""

        env_prefix = "TESTDEMO_"
        env_nested_delimiter = "__"
        case_sensitive = False


# Load settings from environment and config file
_config_file = Path(__file__).parent.parent.parent / "config" / "settings.yaml"
settings = Settings.from_yaml(_config_file) if _config_file.exists() else Settings()
