# @generated by restack-gen
"""
DataPipelineWorkflow workflow.

Auto-generated pipeline from operator expression: DataFetcher → DataProcessor → DataSaver
"""

from data_pipeline.agents.data_fetcher import data_fetcher_activity
from data_pipeline.agents.data_processor import data_processor_activity
from data_pipeline.agents.data_saver import data_saver_activity
from restack_ai import Workflow, step


class DataPipelineWorkflow(Workflow):
    """DataPipelineWorkflow orchestrates multiple resources."""

    @step
    async def execute(self, input_data: dict) -> dict:
        """Execute pipeline workflow."""
        result = input_data

        result = await self.execute_activity(data_fetcher_activity, result)
        result = await self.execute_activity(data_processor_activity, result)
        result = await self.execute_activity(data_saver_activity, result)

        return result
